name: Docker CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mana-store:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/mana-store:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/mana-store:buildcache,mode=max
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            DIRECT_URL=${{ secrets.DIRECT_URL }}

  deploy-to-vps:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Vercel
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          envs: DOCKER_USERNAME
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/mana-store:latest
            docker stop mana-store || true
            docker rm mana-store || true
            docker run -d \
              --name mana-store \
              -p 3000:3000 \
              --restart unless-stopped \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              -e DIRECT_URL="${{ secrets.DIRECT_URL }}" \
              -e NEXTAUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}" \
              -e NEXTAUTH_URL="${{ secrets.NEXTAUTH_URL }}" \
              -e GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
              -e GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
              -e SEPAY_API_KEY="${{ secrets.SEPAY_API_KEY }}" \
              -e SEPAY_BANK_ID="${{ secrets.SEPAY_BANK_ID }}" \
              -e SEPAY_ACCOUNT_NO="${{ secrets.SEPAY_ACCOUNT_NO }}" \
              -e EMAIL_HOST="${{ secrets.EMAIL_HOST }}" \
              -e EMAIL_PORT="${{ secrets.EMAIL_PORT }}" \
              -e EMAIL_USER="${{ secrets.EMAIL_USER }}" \
              -e EMAIL_PASS="${{ secrets.EMAIL_PASS }}" \
              ${{ secrets.DOCKER_USERNAME }}/mana-store:latest
            docker image prune -f
